### ISSUE TITLE
<L5_Gray Hat> Link Wiki của nhóm 

### ISSUE THREAD

**Issue by nhtai** [HCMUS-OSSD/HuongdanThuchanh#16]
https://github.com/HCMUS-OSSD/L5_Gray-Hat/wiki

**Comment by bixycler** [comment]
> *Code Assistant Plugin for Eclipse được xây dựng nhằm mục đích nhắc lệnh khi gặp các từ khóa, **thêm các nhắc lệnh của riêng người lập trình** phục vụ cho nhu cầu lập trinh nhanh chóng và hiệu quả hơn.*

Vậy là nhóm muốn làm nhắc lệnh cho những lệnh "riêng". Nhóm cần đặc tả **thế nào là "riêng"**, vì những cấu trúc cú pháp của ngôn ngữ và những hàm trong các thư viện đều đã được nhắc lệnh một cách mặc định rồi.

**Comment by nhtai** [comment]
Dạ! Em cảm ơn thầy! Nhóm em sẽ thảo luận và xem xét kỹ lưỡng hơn!

**Comment by SangThanh** [comment]
Thưa thầy! Nhiều khi nhắc lệnh tự động có chứa một số biến tự động , những phần mà người lập trình đã quá quen và cứ phải xóa phần dư thừa đó đi và code một biến khác hay dòng lệnh khác. Như vậy sẽ tốn khá nhiều thời gian cho người lập trình có kinh nghiệm. Vì vậy ý em là người dùng có thể chỉnh sửa phần code mẫu theo ý của mình để tiện hơn trong lập trình.

VD: public void dothing()
        {
            throw new NotImplementedException();
        }

Ta phải xóa đi dòng code chính giữa sau đó mới code, thay vì để trống hoặc có một chú thích ở đó dành cho người học ...

**Comment by bixycler** [comment]
Nếu làm thêm cho những cái riêng của mình thì dễ, còn sửa lại những cái của người ta thì có vẻ khó hơn đó.

**Comment by SangThanh** [comment]
Vậy nhóm tụi em làm cái riêng thôi có được không thầy? Mong thầy trả lời.

**Comment by bixycler** [comment]
Thầy nghĩ là chỉ cần làm nhắc lệnh cho những "cái riêng" là đủ. Nhưng Nhóm phải định nghĩa được những "cái riêng" đó là gì.

**Comment by bixycler** [comment]
Thầy @vhphuc cho ý kiến đi nhé. Từ nay thầy Phúc sẽ trực tiếp phụ trách HDTH cho Nhóm này nhé.

**Comment by vhphuc** [comment]
Các bạn cần làm rõ các ý sau đây:

• Người dùng: Cài đặt vào Eclipse để:
Xem các nhắc lệnh có sẵn.
Thay đổi nhắc lệnh có sẵn
Thêm, xóa ,sửa nhắc lệnh do người dùng cung cấp.
• Hệ thống: gợi ý lệnh khi người dùng nhập vào từ khóa, nhấn Space để sử dụng gợi ý khi đó hệ thống tự động điền code vào cho người dùng và đưa con trỏ đến vị trí cần thiết.
• Phi chức năng: Nhắc lệnh nhanh, gợi ý khi chưa hoàn thành từ khóa, điền code chính xác...

=> cụ thể các lệnh nào? cho ví dụ và đưa ra con số cụ thể.
=> các bạn để gì trong phần kế hoạch ? tôi chỉ thấy có mấy chữ này "addffd"
