### ISSUE TITLE
T1_ThePlumper : Thiết kế hệ thống

### ISSUE THREAD

**Issue by lmtam** [HCMUS-OSSD/HuongdanThuchanh#18]
Link release: https://github.com/HCMUS-OSSD/T1_ThePlumper/releases
Link wiki   :  https://github.com/HCMUS-OSSD/T1_ThePlumper/wiki

**Comment by htthanh** [comment]
Ok good. CMS các bạn sử dụng là gì?

**Comment by lmtam** [comment]
Dạ thưa thầy  nhóm em dùng CMS là  WordPress.

**Comment by htthanh** [comment]
OK.
