### ISSUE TITLE
T2_hero: Thiết kế hệ thống

### ISSUE THREAD

**Issue by levanlinh1995** [HCMUS-OSSD/HuongdanThuchanh#19]
release: https://github.com/HCMUS-OSSD/T2_hero/releases

wiki: https://github.com/HCMUS-OSSD/T2_hero/wiki

**Comment by htthanh** [comment]
Mô tả ngắn gọn quá mức, đọc vào cứ như ko đọc. Viết lại.

**Comment by levanlinh1995** [comment]
@htthanh  em đã chỉnh sửa lại, mong thầy xem lại và góp ý cho nhóm em hoàn thiện tốt hơn.
Em cảm ơn thầy.

**Comment by htthanh** [comment]
Ok. Good.
