### ISSUE TITLE
L1_PowerOfPassion: Thiết kế hệ thống

### ISSUE THREAD

**Issue by nguyenan1312023** [HCMUS-OSSD/HuongdanThuchanh#20]
Link Release: https://github.com/HCMUS-OSSD/L1_PowerOfPassion/releases/tag/v0
Link Wiki: https://github.com/HCMUS-OSSD/L1_PowerOfPassion/wiki

**Comment by htthanh** [comment]
Tương đối ổn. Nhớ các chức năng của backend nha

**Comment by nguyenan1312023** [comment]
Dạ, ở yêu cầu 1 thì mình chỉ sử dụng plugin có sẵn và back end mình chỉ thao tác sử dụng các chức năng có trong plugin hỗ trợ sẵn của CMS đó và tự tạo cơ sở dữ liệu phải không thầy? Còn đến cái yêu cầu 3 mới là tự xây dựng plugin có front end và back end, em xin cám ơn thầy
