### ISSUE TITLE
S6_gangoffight: Đặc tả đề tài và kế hoạch thực hiện

### ISSUE THREAD

**Issue by gangoffightplus** [HCMUS-OSSD/HuongdanThuchanh#20]
Bên dưới là link dẫn đến phần đặc tả của nhóm, mong thầy xem qua và cho ý kiến.
https://github.com/HCMUS-OSSD/S6_gangoffight/wiki

**Comment by gangoffightplus** [comment]
Mong thầy góp ý bản đặc tả của nhóm em cần sửa đổi lại những gì không ạ?

**Comment by bixycler** [comment]
Thầy @trphloc review nhé.

**Comment by trphloc** [comment]
Về chức năng thì ổn rồi. Nhưng nhóm liệt kê ra các module nào có sẵn, các module nào nhóm sẽ làm mới hoặc có chỉnh sửa thêm nhé.

**Comment by gangoffightplus** [comment]
Em cám ơn thầy, nhóm em sẽ chỉnh sửa lại.

**Comment by gangoffightplus** [comment]
Rất xin lỗi thầy vì sự chậm trễ này. Nhóm em đã chỉnh sửa lại wiki, mong thầy xem qua.
