### ISSUE TITLE
S1_5M: Thiết kế hệ thống

### ISSUE THREAD

**Issue by nhn12** [HCMUS-OSSD/HuongdanThuchanh#22]
Link releases: https://github.com/HCMUS-OSSD/S1_5M/releases

Link Wiki: https://github.com/HCMUS-OSSD/S1_5M/wiki

**Comment by htthanh** [comment]
OK. Good. Nhưng chưa thấy chức năng backend

**Comment by nhn12** [comment]
thầy ơi, do nhóm em xin chuyển đềi tài từ Orchard sang Wordpress nên V0 này tụi em cập nhật trong v1 luôn được không thầy

**Comment by nhn12** [comment]
Nhóm em đã bổ sung phần Backend - người bán hàng, mong thầy xem xét đóng Issues
cảm ơn Thầy
