### ISSUE TITLE
L3_Hattrick: Thiết kế hệ thống

### ISSUE THREAD

**Issue by sonhoang0611** [HCMUS-OSSD/HuongdanThuchanh#23]
- Link đến release: https://github.com/HCMUS-OSSD/L3_Hattrick/releases/tag/v0

- Link đến wiki: https://github.com/HCMUS-OSSD/L3_Hattrick/wiki

**Comment by htthanh** [comment]
Cần có chức năng ở backend, người bán hàng

**Comment by sonhoang0611** [comment]
@htthanh Dạ em chào thầy! Nhóm em đã bổ sung một số chức năng backend dành cho người bán hàng mà thầy yêu cầu. Mong thầy xem xét giúp nhóm em! Cảm ơn thầy!

**Comment by htthanh** [comment]
Add hình vào wiki nào

**Comment by sonhoang0611** [comment]
Dạ chúng em đã bổ sung hình ảnh vào wiki. Mong thầy xem xét giúp chúng em lại!
