### ISSUE TITLE
[T5_Awesomnium] Wiki đặc tả đề tài và kế hoạch của nhóm

### ISSUE THREAD

**Issue by earlwlkr** [HCMUS-OSSD/HuongdanThuchanh#24]
Đây là Wiki sơ khai của nhóm em, xin thầy xem qua và góp ý:

https://github.com/HCMUS-OSSD/T5_Awesomnium/wiki

**Comment by bixycler** [comment]
Nhóm cần đặc tả các giao diện front-ends và back-ends nữa.

**Comment by earlwlkr** [comment]
Nhóm em đã thực hiện bổ sung, mời thầy @hotuanthanh xem lại ạ.

**Comment by bixycler** [comment]
Thầy @hotuanthanh close ý là "đã chấp nhận" đúng không?

**Comment by bixycler** [comment]
Dùng label "fixed" để xác nhận "đã chấp nhận" nhé.
