### ISSUE TITLE
S3_MaxTeam: Thiết kế hệ thống

### ISSUE THREAD

**Issue by quyen91** [HCMUS-OSSD/HuongdanThuchanh#24]
Link release: https://github.com/HCMUS-OSSD/S3_MaxTeam/releases/tag/v0
Link wiki: https://github.com/HCMUS-OSSD/S3_MaxTeam/wiki

**Comment by htthanh** [comment]
Thầy Định kêu wiki viết mô tả project. Mà click vào empty là sao?

**Comment by quyen91** [comment]
@htthanh bọn em có viết mà thầy

**Comment by htthanh** [comment]
Ok. Đồng ý. Bạn để bên phải, mình ko thấy.
