### ISSUE TITLE
L1_OSS_KHTN : Đặc tả kế hoạch và kế hoạch làm việc của nhóm 

### ISSUE THREAD

**Issue by mrarsenal10** [HCMUS-OSSD/HuongdanThuchanh#25]
Đây là đặc tả đề tài và kế hoạch thực hiện của nhóm em xin mời thầy xem qua ạ .
https://github.com/HCMUS-OSSD/L1_OSS_KHTN/wiki/%C4%90%E1%BA%B7c-t%E1%BA%A3-%C4%91%E1%BB%81-t%C3%A0i
https://github.com/HCMUS-OSSD/L1_OSS_KHTN/wiki/K%C3%AA-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n

**Comment by mrarsenal10** [comment]
Đây là đặc tả đề tài và kế hoạch thực hiện của nhóm em xin mời thầy xem qua ạ .
https://github.com/HCMUS-OSSD/L1_OSS_KHTN/wiki/%C4%90%E1%BA%B7c-t%E1%BA%A3-%C4%91%E1%BB%81-t%C3%A0i
https://github.com/HCMUS-OSSD/L1_OSS_KHTN/wiki/K%C3%AA-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n

**Comment by bixycler** [comment]
"Đặc tả" này không có nội dung gì có thể góp ý được hết. Đề nghị nhóm cho thêm nội dung.

**Comment by mrarsenal10** [comment]
Dạ em sẽ bổ sung thêm.

**Comment by mrarsenal10** [comment]
Em đã sửa lại đặc tả đề tài mong thầy cho ý kiến ạ.

**Comment by bixycler** [comment]
> chức năng: Hiển thị thông tin một file

Ý của nhóm là file nào? Nhóm nên đưa một tình huống cụ thể (usecase) để thấy rõ là người dùng cần biết "tóm tắt nội dung" của 1 file như thế nào, để làm gì, v.v.

**Comment by bixycler** [comment]
>  chức năng:
Hỗ trợ người dùng hiểu rõ về một đối tượng VD: Phần mềm có chức năng mới thì người dùng có thể trỏ con chuột tới để hiểu rõ về chức năng đó hoặc *tìm hiểu về một con vật*: hình dáng, kích thước ...

Thầy vẫn chưa rõ nhóm muốn làm ứng dụng gì. Có vẻ là một ứng dụng hấp dẫn phải thêm/bớt/thay đổi chức năng liên tục, và có cả "con vật" trong đó nữa. Nghe có vẻ thú vị và mang tính tiểu thuyết nhiều nhưng vẫn chưa rõ. Đề nghị nhóm cho một tình huống sử dụng cụ thể hơn.

Những ý tưởng bay bổng này cần phải nhờ thầy @vhphuc duyệt này.

**Comment by mrarsenal10** [comment]
Dạ em mong thầy cho ý kiến ạ.

**Comment by vhphuc** [comment]
Chào em, về bản đặc tả tôi thấy các bạn cần làm rõ một số chỗ:

1. Tooltips thường được sử dụng trên các website, khi rê chuột đến sẽ hiển thị hình ảnh và thông tin của đối tượng đó. Hiện nay CSS HTML and JavaScript cho phép các web designers tạo các tooltip.
      => Các bạn mô tả cụ thể mình sẽ làm cho web app hay desktop app hay cho eclipse ....
2. Hỗ trợ người dùng hiểu rõ về một đối tượng VD: Người dùng có thể trỏ chuột tới icon phần mềm mà không cần click để hiển thị thông tin về phần mềm đó như: +Tên phần mềm
Công ty sản xuất
Phiên bản
Ngày cài đặt
Kích thước file
Khi muốn tìm hiểu về một con vật có tên lạ thông thường chỉ đọc những miêu tả về con vật đó : kích thước của nó, màu sắc, đặc điểm, tooltip bây giờ có thể hỗ trợ bằng cách khi trỏ con chuột tới tên của con vật thì có thể hiển thị hình ảnh của nó để người dùng có thể hiễu rõ hơn.
  => Tôi chưa rõ các bạn muốn làm gì với chức năng này? có thể cho ví dụ không?

**Comment by tttttduong** [comment]
Do bạn nhóm trưởng có nhầm lẫn về phần đặc tả và kế hoạch nên em xin thay mặt nhóm chỉnh sửa lại nội dung hai phần trên cho phù hợp. Mong thầy @bixycler và thầy @vhphuc thông cảm. Chúng em mong được các thầy review lại lần nữa và đóng góp ý kiến để giúp chúng em có thể hoàn thành tốt nhất đồ án môn học này. Em xin thay mặt nhóm cảm ơn thầy @bixycler và thầy @vhphuc  và cũng xin lỗi hai thầy vì sự bất cẩn trên. (Trịnh Đình Dương - 1112060 - tttttduong)

**Comment by vhphuc** [comment]
Các bạn đã update phần nào thì vui lòng đánh dấu vào (tô đậm/gạch dưới/đổi màu).

**Comment by mrarsenal10** [comment]
Em xin chào thầy,
Thưa thầy thầy có thể gia hạn deadline cài plugin thêm 1 ngày nữa được
không ạ ?
Mạng nhà em hôm qua tới giờ ko hiểu sao mấy trang web nước ngoài vào không
được ạ như github còn các trang moodle thì vào bình thường  . Em chỉ xin
thêm 1 ngày để up  lên thôi ạ . Em cám ơn thầy đã xem qua.

Vào 15:55 Ngày 14 tháng 04 năm 2015, vhphuc <notifications@github.com> đã
viết:

**Comment by mrarsenal10** [comment]
Xin thầy cho ý kiện ạ.
