### ISSUE TITLE
T2_Hero: Cài đặt hệ thống

### ISSUE THREAD

**Issue by levanlinh1995** [HCMUS-OSSD/HuongdanThuchanh#27]
link wiki: https://github.com/HCMUS-OSSD/T2_hero/wiki/Thi%E1%BA%BFt-k%E1%BA%BF-h%E1%BB%87-th%E1%BB%91ng

link release:  https://github.com/HCMUS-OSSD/T2_hero/releases/tag/v1

**Comment by htthanh** [comment]
Ok. Good
