### ISSUE TITLE
L1_PowerOfPassion: Cài đặt hệ thống

### ISSUE THREAD

**Issue by nguyenan1312023** [HCMUS-OSSD/HuongdanThuchanh#28]
Link Release v1: https://github.com/HCMUS-OSSD/L1_PowerOfPassion/releases/tag/v1
Link Wiki: https://github.com/HCMUS-OSSD/L1_PowerOfPassion/wiki

**Comment by htthanh** [comment]
Có backend ko

**Comment by nguyenan1312023** [comment]
Dạ thưa thầy trong web bán hàng của nhóm đã có các chức năng về backend rồi ạ, nhóm sẽ bổ sung hình ảnh demo trên wiki. Mong thầy đóng issue sớm.

**Comment by htthanh** [comment]
Ok.

**Comment by nguyenan1312023** [comment]
Nhóm đã bổ sung thông tin và hình ảnh demo về các chức năng backend trong website bán hàng của nhóm trên wiki.

**Comment by nguyenan1312023** [comment]
Nhóm đã bổ sung thông tin và hình ảnh demo về các chức năng backend trong website bán hàng của nhóm trên wiki.

**Comment by htthanh** [comment]
ok
