### ISSUE TITLE
TheEnd: Cài đặt hệ thống

### ISSUE THREAD

**Issue by nguyendatz** [HCMUS-OSSD/HuongdanThuchanh#29]
Release: https://github.com/HCMUS-OSSD/L4_TheEnd/releases/tag/v1
Wiki: https://github.com/HCMUS-OSSD/L4_TheEnd/wiki

**Comment by htthanh** [comment]
Nhóm nào đây?

**Comment by htthanh** [comment]
Rồi wiki đâu

**Comment by nguyendatz** [comment]
Dạ nhóm TheEnd.
Em mới làm wiki trang Home.
Nhóm e gồm e, Sỉ và Nam. Em gọi mấy bạn hoài mà mấy bạn cứ bận.
Em làm luôn nha thầy. Mình e làm được không thầy?
Trang web e đã cài đặt rồi, và có 1 số product mẫu. Còn thiếu viết plugin ạ.

**Comment by nguyendatz** [comment]
Dạ nhóm TheEnd, e mới bổ sung wiki nhưng chưa đầy đủ ạ

**Comment by htthanh** [comment]
Có cái hình ảnh nào đâu mà đầy đủ.

**Comment by nguyendatz** [comment]
Dạ có hình mà thầy, chắc e up hình từ host ngoài nên load lâu, để e up lại trên đây

**Comment by htthanh** [comment]
Vậy thì Sỉ và Nam 0 điểm đồ án nha.

2017-01-03 9:21 GMT+07:00 nguyendatz <notifications@github.com>:

**Comment by nguyendatz** [comment]
Dạ e mới cập nhật lại hình ảnh (trên host github)

**Comment by htthanh** [comment]
ok
