### ISSUE TITLE
L3_Hattrick: Cài đặt hệ thống

### ISSUE THREAD

**Issue by sonhoang0611** [HCMUS-OSSD/HuongdanThuchanh#30]
Link đến Wiki: https://github.com/HCMUS-OSSD/L3_Hattrick/wiki/Wiki-v2
Link đến Release: https://github.com/HCMUS-OSSD/L3_Hattrick/releases/tag/v1

**Comment by htthanh** [comment]
Insert hình vào page wiki luôn nha. Link dropbox thầy ko đọc được.
Và ko thấy phần backend.

**Comment by sonhoang0611** [comment]
@htthanh  Dạ chúng em đã bổ sung, mong thầy xem lại giúp!

**Comment by htthanh** [comment]
OK.
