### ISSUE TITLE
S3_ITers_Đặc Tả Đồ Án và Kế Hoạch thực hiện đồ án

### ISSUE THREAD

**Issue by NgoHoangThang2309** [HCMUS-OSSD/HuongdanThuchanh#31]
Chào thầy!!
   Đây là link wiki của đặc tả đồ án của nhóm em trong đó có mô tả sơ qua về ý tưởng và kế hoạch dự kiến của chúng em: https://github.com/HCMUS-OSSD/S3_ITers/wiki/M%C3%B4-T%E1%BA%A3-%C4%90%E1%BB%93-%C3%81n
Thầy xem qua giúp em với ạ. Em cám ơn!

**Comment by bixycler** [comment]
Thầy @trphloc review nhé.

**Comment by trphloc** [comment]
Chi tiết ra nhé. Admin làm được gì? Khách hàng làm được gì?
Nhóm cần tham khảo thêm các trang bán hàng của các shop để biết thêm

**Comment by trphloc** [comment]
Tạm đóng
