### ISSUE TITLE
S1_5M: Cài đặt hệ thống

### ISSUE THREAD

**Issue by nhn12** [HCMUS-OSSD/HuongdanThuchanh#32]
Release: https://github.com/HCMUS-OSSD/S1_5M/releases/tag/v1
Wiki: https://github.com/HCMUS-OSSD/S1_5M/wiki
Note: nhóm em đã xin thầy chuyển từ CMS Orchard sang CMS Wordpress

**Comment by htthanh** [comment]
Còn backend nữa

**Comment by nhn12** [comment]
Nhóm em có trình bài phần luồng chạy ở Backend ở phía dưới của wiki, hay ý thầy là Backend như thế nào ạ?

**Comment by nhn12** [comment]
Nhóm em đã bổ sung phần Backend - người bán hàng, mong thầy xem xét đóng Issues
cảm ơn Thầy

**Comment by htthanh** [comment]
OK
