### ISSUE TITLE
L2_Freedom: Cài đặt hệ thống

### ISSUE THREAD

**Issue by lynxerious** [HCMUS-OSSD/HuongdanThuchanh#33]
Release: https://github.com/HCMUS-OSSD/L2_Freedom/releases/tag/v1
Wiki: https://github.com/HCMUS-OSSD/L2_Freedom/wiki

**Comment by lynxerious** [comment]
Nhóm em xin lỗi thầy vì đã tạo nhầm issue trên Github private của nhóm.

**Comment by htthanh** [comment]
Chưa có phần backend nhá

**Comment by lynxerious** [comment]
Thưa thầy, nhóm em đã thêm mục backend vào wiki ạ.
https://github.com/HCMUS-OSSD/L2_Freedom/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng-Backend-%C4%91%E1%BB%83-th%E1%BB%B1c-hi%E1%BB%87n-b%C3%A1n-h%C3%A0ng

**Comment by htthanh** [comment]
ok
