### ISSUE TITLE
Đặc tả đồ án và kế hoạch thực hiện của nhóm T4_LazyTeam

### ISSUE THREAD

**Issue by ductan9400** [HCMUS-OSSD/HuongdanThuchanh#35]
https://github.com/HCMUS-OSSD/T4_LazyTeam/wiki

**Comment by ChuanGz** [comment]
REPORTER của nhóm em đã tạo issue trên HDTH rồi, Nhóm em là LazyTeam, nhờ thầy duyệt qua cho nhóm em

**Comment by bixycler** [comment]
Thầy @trphloc duyệt xem nhé.

**Comment by trphloc** [comment]
Không hiểu ý của nhóm. Tạo website của nhóm sao lại làm bằng forum :-s

**Comment by bixycler** [comment]
@trphloc> *Tạo website của nhóm sao lại làm bằng forum*
Đây là nhóm duy nhất làm chủ đề web sử dụng open source forum mà thầy Lộc ra đề đó!

**Comment by ChuanGz** [comment]
Chào thầy, em thấy chủ đề cũng hay nên chọn, nhóm em đồng ý kiến với em. Em
đã làm 1 kế hoạch start 1 rồi, kế hoạch chi tiết em cần xíu thời gian tim
hiểu
Đây là bản kế hoạch cho tuần đầu
https://drive.google.com/open?id=0Byhfn3NPC4JjRDFVOXNTdllXOE0&authuser=0

Vào 14:15 Ngày 12 tháng 04 năm 2015, Lê Xuân Định <notifications@github.com>
đã viết:

**Comment by trphloc** [comment]
Ý của tôi là chủ đề của nhóm.

Chỉ là tạo website cho 1 cửa hàng thời trang, tại sao lại dùng forum mà không phải là các CMS

**Comment by ductan9400** [comment]
Bọn em gà mờ, chưa biết nên xài công cụ nào. Vậy theo thầy là bọn em nên sử dụng CMS ạ?

**Comment by trphloc** [comment]
Không có khái niệm gà mờ nhé. 
Nhóm tìm và đọc kỹ thông tin xem chủ đề/ý tưởng của nhóm phù hợp với loại nào nhé. Xong rồi quyêt định để tôi duyệt.

**Comment by ChuanGz** [comment]
Chào thầy,
Em là nhóm trưởng hiện tại của nhóm này. Nhóm em chọn đề tài về open source
forum, sau đó nhóm thấy phần này thầy yêu cầu là, à, tìm hiểu và cài đặt
một website bán hàng.

Nếu chỉ là website để quảng cáo cho cửa hàng thôi, em chắc chắn là open
source forum sẽ không phù hợp, nhưng để quản lý database khách hàng, quản
lý bán hàng, (và nhiều "vấn đề" khác nhóm em đang tìm hiểu để đưa vào) thì
có nó sẽ hợp lý hơn đúng không ạ?

 Nhóm em chọn nhóm đề tại trước rồi mới chọn đề tài cụ thể (*đi từ tổng
quát đến chi tiết*), nên câu hỏi của thầy "Tại sao nhóm em lại chọn open
source forum cho website bán hàng", theo em nghĩ là em chọn open source
forum không có vấn đề gì, chủ yếu là cái website của nhóm em chọn chức năng
gì mà  cần sử dụng open source forum

Bạn trong nhóm em nói "*gà mờ*" có lẽ là do bạn ấy đang khó hiểu về những ý
kiến em phổ biến không khớp với ý thầy chia sẻ. Bạn ấy nghĩ là, nếu như
muốn làm về open source forum chỉ có thể là website bán hàng (như trong
file *DoanCuoiKy.pdf*). Nhóm em có tiêu chí là chọn cái mà trước giờ chưa
ai trong nhóm đã làm, để sự khó khăn trong quá trình làm đồ án sẽ cho chúng
em nhiều kinh nghiệm.

 Cảm ơn những chia sẻ của thầy, mong nhận hồi âm của thầy sớm!
Thanh Nhàn

Vào 13:26 Ngày 13 tháng 04 năm 2015, trphloc <notifications@github.com> đã
viết:

**Comment by bixycler** [comment]
@ChuanGz > *Bạn ấy nghĩ là, nếu như muốn làm về open source forum chỉ có thể là website bán hàng (như trong file *DoanCuoiKy.pdf*)*
Đúng là phần mô tả về chủ đề "Website sử dụng open-source forum" trong DoanCuoiKy.pdf chưa nói rõ những đặc trưng của Website sử dụng open-source forum khác với Website sử dụng open-source CMS như thế nào. 

Cũng chỉ có 1 nhóm chọn forum nên thầy @trphloc làm rõ trực tiếp cho nhóm ở đây luôn nhé.

**Comment by trphloc** [comment]
Ah, xin lỗi nhóm, tôi bị lỗi khi soạn tập tin mô tả, forum chỉ phù hợp cho dạng hệ thống trao đổi thông tin, rao vặt, hỏi đáp, ... thì phù hợp hơn.
Nhóm có thể chuyển qua hệ thống thông tin về các cửa hàng thời trang.

**Comment by bixycler** [comment]
Nhóm này thầy thấy chỉ có mỗi @ChuanGz làm việc rất tội nghiệp, nên đồng ý cho gộp với nhóm @HCMUS-OSSD/l6_whisky ==> Chuyển chủ đề sang #45 nhé.

**Comment by ChuanGz** [comment]
Cảm ơn thầy bixycler đã chia sẻ. sau khi gộp nhóm thì nhóm em sẽ không còn hoạt động nữa phải không ạ
