### ISSUE TITLE
S2_HNTV_T : Đặc tả đề tài và Kế hoạch thực hiện của nhóm

### ISSUE THREAD

**Issue by hdbd789** [HCMUS-OSSD/HuongdanThuchanh#36]
Đây là wiki của nhóm, nhờ thầy xem qua :
https://github.com/HCMUS-OSSD/S2_HNTV_T/wiki

**Comment by hotuanthanh** [comment]
OK.

**Comment by bixycler** [comment]
Trong đề bài Đồ án Cuối kỳ có yêu cầu chức năng "Khuyến mãi" mà chưa thấy nhóm nêu trong đặc tả. Nhờ thầy @hotuanthanh xem lại nhé.

**Comment by bixycler** [comment]
Thầy @trphloc review nhé.

**Comment by trphloc** [comment]
Các trang như qui định, liên hệ thì thế nào em?

**Comment by hdbd789** [comment]
Chào thầy, 
Đây mới chỉ là bản đặc tả tổng quát của nhóm để khái quát các chức chính cho trang web. Nhóm chúng em sẽ cập nhật và chỉnh sửa thêm vào bản đặc tả chi tiết các chức năng hơn. Mong các thầy thông cảm.
Em xin cảm ơn các thầy đã cho nhóm em ý kiến quan trọng, nhóm em sẽ bổ sung và chỉnh sửa vào wiki.

**Comment by hdbd789** [comment]
Chào thầy,
Nhóm em đã cập nhật và chỉnh sửa wiki , mong  thầy xem và cho ý kiến để nhóm em chỉnh sửa được tốt hơn.
Em xin cảm ơn thầy,

**Comment by hotuanthanh** [comment]
Ok. Tốt.
