### ISSUE TITLE
L2_AIMABIET : Đặc tả đề tài và Kế hoạch thực hiện của nhóm.

### ISSUE THREAD

**Issue by jamesbrad1309** [HCMUS-OSSD/HuongdanThuchanh#38]
Link đặc tả đề tài và Kế hoạch thực hiện của nhóm L2_AIMABIET mong thầy xem qua :

- [Đặc tả đề tài](https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/2.-%C4%90%E1%BA%B7c-t%E1%BA%A3-y%C3%AAu-c%E1%BA%A7u)
- [Kế hoạch nhóm](https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/3.-K%E1%BA%BF-ho%E1%BA%A1ch-nh%C3%B3m)

**Comment by hotuanthanh** [comment]
Front end thì ok rồi, nhưng mà back end ko có. Đặc tả gấp ngay.

**Comment by bixycler** [comment]
Như thầy Thanh đã nói. Nhóm bổ sung gấp phần đặc tả back-end: Các chức năng quản lý của admin.

**Comment by khanhicetea** [comment]
@bixycler @hotuanthanh mong thầy xem lại giúp nhóm em ạ

https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/2.-%C4%90%E1%BA%B7c-t%E1%BA%A3-y%C3%AAu-c%E1%BA%A7u

**Comment by khanhicetea** [comment]
Nhóm em mới cập nhật lại Wiki Đặc tả thêm phần plugins khuyến mãi, mong thầy kiểm tra lại.

https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/2.-%C4%90%E1%BA%B7c-t%E1%BA%A3-y%C3%AAu-c%E1%BA%A7u

**Comment by bixycler** [comment]
Đã duyệt.
