### ISSUE TITLE
T3_Heracles: Đặc tả đồ án nhóm Heracles

### ISSUE THREAD

**Issue by hoangtuhatde** [HCMUS-OSSD/HuongdanThuchanh#39]
Em nhầm folk với trang thật nên cứ nghĩ không tạo được issue, thầy thông cảm ạ.
https://github.com/hcmus-heracles/doancuoiky/wiki

**Comment by bixycler** [comment]
Nhóm phải đặt nhánh chính trên **repo của lớp** nhé (https://github.com/HCMUS-OSSD/T3_Heracles)

**Comment by bixycler** [comment]
hoangtuhatde commented 20 hours ago:
Em đã đưa wiki vào đúng chỗ, thầy review giúp ạ
https://github.com/HCMUS-OSSD/T3_Heracles/wiki

**Comment by hotuanthanh** [comment]
Nhóm liệt kê rõ ràng các chức năng frontend và backend.

**Comment by hoangtuhatde** [comment]
Thầy ơi em có cần viết ra thêm 1 chương trình để quản lý trang quảng cáo nào sẽ hiện ra hay cài đặt cố định vài trang web để demo?

**Comment by hoangtuhatde** [comment]
Đã cập nhật backend và frontend ạ. Em sẽ tiếp tục cập nhật khi nhận được câu trả lời của thầy cho câu hỏi phía trên

**Comment by hotuanthanh** [comment]
Plugin giúp admin quản lí các quảng cáo: tên quảng cáo, kích thước, đặt ở đâu, đặt ở những trang nào, thời gian đặt từ ngày giờ nào đến ngày giờ nào? ...

**Comment by hoangtuhatde** [comment]
Em đã cập nhật thêm backend

**Comment by hotuanthanh** [comment]
Ok.
