### ISSUE TITLE
T6_T2: Nhờ thầy xem đặt tả đề tài giúp nhóm em.

### ISSUE THREAD

**Issue by LhGiang** [HCMUS-OSSD/HuongdanThuchanh#44]
Đặt tả trên [Wiki] (https://github.com/HCMUS-OSSD/T6_2G/wiki/%C4%90%E1%BA%B7t-t%E1%BA%A3-%C4%91%E1%BB%81-t%C3%A0i-v%C3%A0-k%E1%BA%BF-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n)

**Comment by hotuanthanh** [comment]
Front end nên có thêm chức năng xem các order đã đặt, status các order
Back end nên có thêm xem danh sách order, update status order

**Comment by LhGiang** [comment]
Thưa thầy, em đã thêm các chức năng trên.
Đây là link ạ [Wiki] (https://github.com/HCMUS-OSSD/T6_2G/wiki/%C4%90%E1%BA%B7t-t%E1%BA%A3-%C4%91%E1%BB%81-t%C3%A0i-v%C3%A0-k%E1%BA%BF-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n)
