### ISSUE TITLE
L6_Whisky: Nhờ thầy xem dùm đặc tả của nhóm em

### ISSUE THREAD

**Issue by dchlong** [HCMUS-OSSD/HuongdanThuchanh#45]
[Đặc tả] (https://github.com/HCMUS-OSSD/L6_Whisky/wiki/%C4%90%E1%BA%B7c-t%E1%BA%A3-v%C3%A0-k%E1%BA%BF-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n-%C4%91%E1%BB%93-%C3%A1n-cu%E1%BB%91i-k%C3%AC)

**Comment by hotuanthanh** [comment]
Nhóm phải liệt kê rõ các chức năng sẽ làm, ko 3 chấm, ko ghi là tương tự website khác.

**Comment by dchlong** [comment]
Dạ thưa thầy, nhóm em đã sửa lại ạ, thầy coi lại và góp ý thêm giúp nhóm em. Em cảm ơn thầy.

**Comment by bixycler** [comment]
Phần khái quát như vậy là ổn. Nhưng Nhóm cần đặc tả rõ 2 giao diện front ends (cho khách viếng thăm chưa có tài khoản và cho khách hàng đã có tài khoản) và giao diện back end (cho quản trị viên).

**Comment by dchlong** [comment]
Em chào thầy, em đã sửa thêm, mong thầy góp ý ạ. Em cảm ơn thầy.

**Comment by bixycler** [comment]
Vậy nội dung khuyến mãi từ đâu ra? Ai quản lý? (Thầy chỉ thấy "Tự xây dựng module/plugin đăng tin khuyến mãi" nhưng không thấy đặc tả trong front-ends hay back-end)

**Comment by bixycler** [comment]
Gộp nhóm T4 qua đây và thầy @trphloc trực tiếp đảm nhiệm nhé.

**Comment by dchlong** [comment]
Em chào thầy, em đã mô tả thêm về plugin đăng khuyến mãi, mong thầy góp ý. Em cảm ơn thầy

**Comment by hotuanthanh** [comment]
Thời gian quảng cáo: từ mấy giờ, ngày mấy đến mấy giờ ngày mấy? đặt quảng cáo ở những trang nào? làm sao load những sản phẩm tương ứng với quảng cáo đó lên?

**Comment by dchlong** [comment]
Em chào thầy, em đã cập nhật thêm mô tả. Mong thầy góp ý ạ. Em cảm ơn thầy.

**Comment by ChuanGz** [comment]
Chào Long, phần triển khai hệ thống, mình chưa được tham gia, các việc sau bạn nhớ phân công mình với nhé. Thân
