### ISSUE TITLE
L4_TheSun: Nhờ Thầy xem hộ em bản đặt tả

### ISSUE THREAD

**Issue by DangNhutYen1212536** [HCMUS-OSSD/HuongdanThuchanh#47]
Chi tiết bản đặc tả 
[wiki](https://github.com/HCMUS-OSSD/L4_The-Sun/wiki/TheSun:-%C4%90%E1%BA%B7c-t%E1%BA%A3-%C4%91%E1%BB%93-%C3%A1n-v%C3%A0-k%E1%BA%BF-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n)

**Comment by bixycler** [comment]
Nhóm chưa nói được website này bán hàng gì.
Nhóm cần đặc tả rõ 2 giao diện front ends (cho khách viếng thăm chưa có tài khoản và cho khách hàng đã có tài khoản) và giao diện back end (cho quản trị viên).

**Comment by DangNhutYen1212536** [comment]
Dạ, nhóm em đã update lại rồi ạ.

**Comment by bixycler** [comment]
OK, duyệt đặc tả.
