### ISSUE TITLE
<L5_Gray Hat> Deadline 2 - Triển khai hệ thống

### ISSUE THREAD

**Issue by nhtai** [HCMUS-OSSD/HuongdanThuchanh#49]
[Link Wiki của nhóm] (https://github.com/HCMUS-OSSD/L5_Gray-Hat/wiki)

**Comment by vhphuc** [comment]
Phần đặc tả đồ án, sau khi comment vẫn không thấy các bạn cập nhật.

**Comment by bixycler** [comment]
Thầy @vhphuc comment lộn chỗ rồi. Đây là thread của Deadline 2. Đáng lẽ phải nói là:
- "Quá Trình Triển Khai Hệ Thống" chỉ có 3 chấm (...) là sao? Các bạn muốn giữ chỗ cũng không được đâu vì **điểm quá trình được chấm trên ngày hoàn thành nội dung** chứ không phải ngày mở issue.

**Comment by bixycler** [comment]
Mà lỗi cũng do nhóm dán link không chính xác. Với deadline 2 thì nhóm phải dán link tới tận nơi thế này: 
https://github.com/HCMUS-OSSD/L5_Gray-Hat/wiki/Qu%C3%A1-Tr%C3%ACnh-Tri%E1%BB%83n-Khai-H%E1%BB%87-Th%E1%BB%91ng

**Comment by nhtai** [comment]
Dạ! Xin lỗi thầy! Nhóm em đã cập nội dung triển khai hệ thống!

**Comment by nhtai** [comment]
Nhóm em đã cập nhật Đặc tả đề tài và kế hoạch thực hiện đồ án!

**Comment by vhphuc** [comment]
Nhóm các bạn cử đại diện gặp tôi sau lễ, các bạn cũng chuẩn bị luôn câu hỏi để thảo luận.
Tôi có thể gặp các bạn vào: chiều T2, 04 tháng 5, 17h30, phòng BM CNPM I.82.
Các bạn gửi mail xác nhận với tôi nhé. #vhphuc at fit.hcmus.edu.vn
Thân mến.
