### ISSUE TITLE
T3_Heracles: Cập nhật wiki

### ISSUE THREAD

**Issue by hoangtuhatde** [HCMUS-OSSD/HuongdanThuchanh#51]
Em đã đưa wiki vào đúng chỗ, thầy review giúp ạ
https://github.com/HCMUS-OSSD/T3_Heracles/wiki

**Comment by bixycler** [comment]
Các bạn sửa lại thì cập nhật vô issue cũ (#39) nhé, không tạo issue mới khi issue cũ chưa close nhé.
Đóng issue này vì vì trùng với #39
