### ISSUE TITLE
L4_TheSun: [Nộp deadline lần 2] Triển khai hệ thống

### ISSUE THREAD

**Issue by DangNhutYen1212536** [HCMUS-OSSD/HuongdanThuchanh#52]
Chi tiết bài làm: [wiki](https://github.com/HCMUS-OSSD/L4_The-Sun/wiki/Quy-Tr%C3%ACnh-Tri%E1%BB%83n-Khai-H%E1%BB%87-Th%E1%BB%91ng-Wordpress---WooCommerce-l%C3%AAn-Server)

**Comment by bixycler** [comment]
"hdvnbits.net", Nhóm mua tên miền luôn hả, chịu chơi đó :grinning:

**Comment by bixycler** [comment]
OK, đã duyệt.
