### ISSUE TITLE
<L2_ABC> Triển khai hệ thống

### ISSUE THREAD

**Issue by ghost** [HCMUS-OSSD/HuongdanThuchanh#52]
Link release: https://github.com/HCMUS-OSSD/L2_ABC/releases/tag/v1
Link wiki: https://github.com/HCMUS-OSSD/L2_ABC/wiki/Thi%E1%BA%BFt-k%E1%BA%BF-giao-di%E1%BB%87n

assignee = @htthanh

**Comment by htthanh** [comment]
2 links: Page not found???

**Comment by ghost** [comment]
Dạ thưa thầy @htthanh  trong quá trình làm do phiên bản template của tụi em cũ nên bị lỗi không khắc phục được, tụi em tính làm lại bằng template khác và sẽ nộp lại hàng tuần trên github mong thầy cho ý kiến ! em cảm ơn.

**Comment by htthanh** [comment]
Ok. Nhưng nhanh lên!!!
