### ISSUE TITLE
L2_AIMABIET-[Quá trình triển khai hệ thống] - Deadline 2

### ISSUE THREAD

**Issue by jamesbrad1309** [HCMUS-OSSD/HuongdanThuchanh#53]
Nộp deadline 2 của nhóm AIMABIET: [link wiki](https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/4.-Qu%C3%A1-tr%C3%ACnh-tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng)

**Comment by bixycler** [comment]
Triển khai OK. Quay lại hoàn thành đặc tả (phần back-end: Các chức năng quản lý của admin) ở issue #38 nhé.
