### ISSUE TITLE
[T5_Awesomnium] Quá trình triển khai hệ thống

### ISSUE THREAD

**Issue by earlwlkr** [HCMUS-OSSD/HuongdanThuchanh#54]
Quá trình triển khai hệ thống của nhóm:

https://github.com/HCMUS-OSSD/T5_Awesomnium/wiki/Deployment

**Comment by hotuanthanh** [comment]
Tốt. Cho thầy xem hình chụp các chức năng nào

**Comment by earlwlkr** [comment]
Hình chụp một vài chức năng em đã để vào trang wiki riêng [này](https://github.com/HCMUS-OSSD/T5_Awesomnium/wiki/Features), mời thầy @hotuanthanh kiểm tra lại ạ.

**Comment by hotuanthanh** [comment]
OK, tốt.
