### ISSUE TITLE
S5: Bboy_Kute: Đặc tả đề tài và kế hoạch thực hiện (deadline 1)

### ISSUE THREAD

**Issue by hvhieu** [HCMUS-OSSD/HuongdanThuchanh#58]
https://github.com/HCMUS-OSSD/S5_BBoy-Kute/wiki

**Comment by bixycler** [comment]
@hvhieu đóng issue này là vì lý do gì? Có muốn thầy duyệt hay không? Thầy @vhphuc xem xét nhé.

**Comment by hvhieu** [comment]
dạ, để em sửa lại .

**Comment by vhphuc** [comment]
Các bạn chỉ nêu chung chung những chức năng mà chưa giải thích rõ ràng.

Ví dụ: chức năng nào có sẵn => chỉ cần tìm hiểu và sử dụng / hoặc chưa có => cần cài đặt thêm.

Phần kế hoạch thực hiện cũng chưa nêu cụ thể thời gian và khối lượng công việc cần làm, người phụ trách thực hiện.

Phần demo vẫn chưa thể hiện được gì cả.
