### ISSUE TITLE
[S5_Bboy_Kute] Quá trình triển khai hệ thống

### ISSUE THREAD

**Issue by hvhieu** [HCMUS-OSSD/HuongdanThuchanh#59]
https://github.com/HCMUS-OSSD/S5_BBoy-Kute/wiki/Qu%C3%A1-tr%C3%ACnh-tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng

**Comment by bixycler** [comment]
Thầy @vhphuc xem xét nhé.

**Comment by vhphuc** [comment]
Các bạn chỉ nêu chung chung những chức năng mà chưa giải thích rõ ràng.

Ví dụ: chức năng nào có sẵn => chỉ cần tìm hiểu và sử dụng / hoặc chưa có => cần cài đặt thêm.

Phần kế hoạch thực hiện cũng chưa nêu cụ thể thời gian và khối lượng công việc cần làm, người phụ trách thực hiện.

Phần demo vẫn chưa thể hiện được gì cả.

**Comment by hvhieu** [comment]
@vhphuc : thầy có thể nói rõ hơn phần demo tụi em cần phải làm cụ thể gì được ko ? Tại bọn em thấy yêu cầu: "Triển khai trang web của đề tài lên một host free (server) trên mạng. (Chỉ cần config trang chính để nhận ra sản phẩm của Nhóm.)" nên tụi em làm như vậy. Mong thầy góp ý hơn.

**Comment by vhphuc** [comment]
Nhóm các bạn cử đại diện gặp tôi sau lễ, các bạn cũng chuẩn bị luôn câu hỏi để thảo luận.
Tôi có thể gặp các bạn vào: chiều T2, 04 tháng 5, 17h30, phòng BM CNPM I.82.
Các bạn gửi mail xác nhận với tôi nhé. #vhphuc at fit.hcmus.edu.vn
Thân mến.
