### ISSUE TITLE
Các trưởng nhóm yêu cầu cấp quyền "team maintainer"

### ISSUE THREAD

**Issue by bixycler** [HCMUS-OSSD/HuongdanThuchanh#6]
Mỗi trưởng nhóm sau khi nhận lời mời vào team tương ứng thì comment lên đây để yêu cầu GV cấp quyền "nhóm trưởng" theo mẫu sau:

> Nhóm @HCMUS-OSSD/<mã_tên nhóm> xin cấp quyền nhóm trưởng.

**Comment by nhn12** [comment]
Nhóm @HCMUS-OSSD/S1_5M xin cấp quyền nhóm trưởng

**Comment by Izker** [comment]
Nhóm @HCMUS-OSSd/T3_BLIZT xin cấp quyền nhóm trưởng

**Comment by nguyenan1312023** [comment]
Nhóm @HCMUS-OSSD/L1_PowerOfPassion xin cấp quyền nhóm trưởng

**Comment by bixycler** [comment]
@Izker  phải "accept invitation" để vào nhóm trước.

**Comment by quyen91** [comment]
Nhóm @HCMUS-OSSD/S3_MaxTeam xin cấp quyền nhóm trưởng

**Comment by Izker** [comment]
Nhóm @HCMUS-OSSD/t3_blizt xin cấp quyền nhóm trưởng

**Comment by bixycler** [comment]
@quyen91 phải "accept invitation" để vào nhóm trước.

**Comment by quyen91** [comment]
@bixycler thầy ơi em không nhận được mail invite ạ, mail của em (doa9595@gmail.com)

**Comment by bixycler** [comment]
@quyen91, thầy đã add, (xin lỗi hồi nãy quên add).

**Comment by quyen91** [comment]
@bixycler dạ em đã nhận được mail, cảm ơn thầy ạ

**Comment by bixycler** [comment]
Đóng issue này vì không cần quyền "nhóm trưởng" nữa. Các nhóm trưởng vào trực tiếp repo nhóm mình, tab Settings, mục Collaborators & Teams, kéo xuống phần Collaborators để mời thành viên.
