### ISSUE TITLE
[L6_Whisky] Quá trình triển khai hệ thống

### ISSUE THREAD

**Issue by dchlong** [HCMUS-OSSD/HuongdanThuchanh#60]
Quá trình triển khai hệ thống của nhóm: [Link] (https://github.com/HCMUS-OSSD/L6_Whisky/wiki/Qu%C3%A1-tr%C3%ACnh-tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng)

**Comment by bixycler** [comment]
Thầy @trphloc xem nhé.

**Comment by trphloc** [comment]
Tiếp tục làm theo đặc tả nhé

**Comment by bixycler** [comment]
Thầy @trphloc gắn nhãn "fixed" hoặc "wontfix" hoặc "invadid" khi close nhé.
