### ISSUE TITLE
[S3_ITers] Quá trình triển khai hệ thống 

### ISSUE THREAD

**Issue by NgoHoangThang2309** [HCMUS-OSSD/HuongdanThuchanh#61]
Đây là quá trình triển khai hệ thông của nhóm em! Hiện tại nhóm chưa config được nhiều. Mong thầy xem qua giúp em. Em cám ơn thầy!!
https://github.com/HCMUS-OSSD/S3_ITers/wiki/TRI%E1%BB%82N-KHAI-H%E1%BB%86-TH%E1%BB%90NG

**Comment by trphloc** [comment]
Triển khai lên host thật luôn nha, xong tiếp tục làm theo đặc tả

**Comment by NgoHoangThang2309** [comment]
Dạ em chào thầy!
  Em đã upload template lên host free rồi ạ!! Em quên mất việc đưa link trang web vào link wiki, em đã thêm vào rồi rồi ạ. Và đây là link trang template chúng em dự định sẽ thay đổi lại ạ. banhangonline.890m.com. Mong thầy xem lại giúp em!! 
  Em cám ơn Thầy
