### ISSUE TITLE
L3_The-Last Đặc tả yêu cầu, kế hoạch thực hiện

### ISSUE THREAD

**Issue by nguyenhuuthuan94** [HCMUS-OSSD/HuongdanThuchanh#66]
https://github.com/HCMUS-OSSD/L3_The-Last/wiki/%C4%90%E1%BA%B7c-t%E1%BA%A3-y%C3%AAu-c%E1%BA%A7u,-k%E1%BA%BF-ho%E1%BA%A1ch-th%E1%BB%B1c-hi%E1%BB%87n

**Comment by bixycler** [comment]
Nhóm L3.The Last không có hoạt động gì trên github/source, cũng không lên gặp gv LXĐịnh khi được hẹn (thông báo qua moodle & email). Nếu tới cuối buổi học lý thuyết tuần sau (21/5) mà Nhóm không có tiến triển để trình cho GV LXĐịnh xem thì Nhóm sẽ được *0 điểm thực hành*.

**Comment by bixycler** [comment]
Đồ án cuối kỳ của nhóm (L3.The-Last) đã kết thúc ở Deadline 1 này nhé. Không cần phải làm tiếp các deadline sau nữa.
