### ISSUE TITLE
S6_gangoffight: Triển khai hệ thống

### ISSUE THREAD

**Issue by gangoffightplus** [HCMUS-OSSD/HuongdanThuchanh#67]
Nhóm đã triển khai trang web bán di động online lên website. Mong thầy xem qua trên wiki và đóng góp ý kiến.
https://github.com/HCMUS-OSSD/S6_gangoffight/wiki/Tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng

**Comment by trphloc** [comment]
Lỗi, không chạy được

**Comment by gangoffightplus** [comment]
Nhóm đã cập nhật link lại
http://gangoffightplus.bugs3.com/ProjectA

**Comment by gangoffightplus** [comment]
Link trang web của nhóm: https://github.com/HCMUS-OSSD/S6_gangoffight/wiki/Tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng

**Comment by trphloc** [comment]
Đã chạy lên
