### ISSUE TITLE
S2_HNTV_T : Triển khai hệ thống

### ISSUE THREAD

**Issue by hdbd789** [HCMUS-OSSD/HuongdanThuchanh#68]
Nhóm đã triển khai trang web bán thời trang online lên website. Mong thầy xem qua và cho ý kiến đánh giá cho nhóm em.Em xin cảm ơn.
link tới trang wiki :https://github.com/HCMUS-OSSD/S2_HNTV_T/wiki/%C4%90%C6%B0%E1%BB%9Dng-link-web

**Comment by trphloc** [comment]
Nhóm tiếp tục triển khai tiếp theo mô tả của nhóm nhé

**Comment by hdbd789** [comment]
Dạ, em cảm ơn thầy

**Comment by hdbd789** [comment]
Dạ, em cảm ơn thầy
