### ISSUE TITLE
L3_The-Last Triển khai hệ thống

### ISSUE THREAD

**Issue by nguyenhuuthuan94** [HCMUS-OSSD/HuongdanThuchanh#69]
https://github.com/HCMUS-OSSD/L3_The-Last/wiki/Tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng

**Comment by bixycler** [comment]
Đồ án cuối kỳ của nhóm (L3.The-Last) đã kết thúc ở Deadline 1 (#66), không cần phải làm tiếp các deadline sau nữa.
