### ISSUE TITLE
L1_OSS_KHTN : Triển Khai Hệ Thống

### ISSUE THREAD

**Issue by mrarsenal10** [HCMUS-OSSD/HuongdanThuchanh#71]
https://github.com/HCMUS-OSSD/L1_OSS_KHTN/wiki/Tri%E1%BB%83n-khai-h%E1%BB%87-th%E1%BB%91ng
Thưa thầy, em xin lỗi vì sự chậm trễ, em mong được thầy tiếp tục cho nhóm em hoàn thành đồ án cuối kì 
Em xin cám ơn thầy.

**Comment by vhphuc** [comment]
Các bạn phải thể hiện được sự nghiêm túc trong bài làm của nhóm.

**Comment by mrarsenal10** [comment]
Dạ em xin lỗi thầy vì chậm trễ, em không hiểu sao mạng nhà em tối không vào
được các trang nước ngoài sáng hôm sau cũng vậy, em xin thầy cho nhóm em
một cơ hội em xin hứa sẽ không tái phạm nữa em cám ơn thầy.

**Comment by tttttduong** [comment]
Thầy @vhphuc  cho em hỏi: chúng em cần enhancement  thêm những gì nữa ạ?

**Comment by vhphuc** [comment]
Nhóm các bạn cử đại diện gặp tôi sau lễ, các bạn cũng chuẩn bị luôn câu hỏi để thảo luận.
Tôi có thể gặp các bạn vào: chiều T2, 04 tháng 5, 17h30, phòng BM CNPM I.82.
Các bạn gửi mail xác nhận với tôi nhé. #vhphuc at fit.hcmus.edu.vn
Thân mến.

**Comment by bixycler** [comment]
Nhóm đặt tài liệu sai chỗ rồi. Đáng lẽ phải **để ở wiki của Nhóm**, mà nhóm lại để ở wiki của repo HuongdaThuchanh (của GV).

**Comment by mrarsenal10** [comment]
Dạ em xin lỗi , để em sửa lại .
