### ISSUE TITLE
[L2_AIMABIET] - Deadline 3 : Thiết kế hệ thống

### ISSUE THREAD

**Issue by jamesbrad1309** [HCMUS-OSSD/HuongdanThuchanh#76]
Chào thầy,

Nhóm em xin nộp Deadline 3

Release : [Deadline3 Release](https://github.com/HCMUS-OSSD/L2_AIMABIET/releases/tag/Deadline3)
Wiki : [5. Đặc tả thiết kế hệ thống](https://github.com/HCMUS-OSSD/L2_AIMABIET/wiki/5.-Thi%E1%BA%BFt-k%E1%BA%BF-h%E1%BB%87-th%E1%BB%91ng)

Cảm ơn thầy.

**Comment by bixycler** [comment]
"Khi hết khuyến mãi, chỉ cần vào set lại Visibility thành Draft là có thể tắt khuyến mãi này."
Nên wrap cái hành động "set lại Visibility thành Draft" thành 1 hành động "kết thúc khuyến mãi". Có thể đặt  hành động mới đó trong Bulk actions hoặc bên ngoài và trên trang edit post.

**Comment by khanhicetea** [comment]
Chào thầy,

Em nghĩ chức năng đó thực sự có chút dư thừa vì cơ bản Wordpress đã hỗ trợ việc đó :smile: 

Chọn các khuyến mãi cần đóng hoặc mở một lúc, chọn Bulk Actions là Edit > Apply
Tiếp đến chọn trạng thái là Draft hoặc Published và nhấn Update là xong :D

Demo 
![bulk action change visibility](https://cloud.githubusercontent.com/assets/4528223/7852853/1c78ac58-052f-11e5-8480-dba501601285.png)

P/s : em đã cập nhật hướng dẫn vào trong wiki ạ

**Comment by bixycler** [comment]
Thôi, tạm vậy đi. Dù sao đó cũng là gợi ý của thầy.
Duyệt.
