### ISSUE TITLE
L3_The-Last Thiết kế hệ thống

### ISSUE THREAD

**Issue by nguyenhuuthuan94** [HCMUS-OSSD/HuongdanThuchanh#82]
https://github.com/HCMUS-OSSD/L3_The-Last/releases/tag/v1.0
https://github.com/HCMUS-OSSD/L3_The-Last/wiki/Deadline3:-Thi%E1%BA%BFt-k%E1%BA%BF-h%E1%BB%87-th%E1%BB%91ng

**Comment by bixycler** [comment]
Đồ án cuối kỳ của nhóm (L3.The-Last) đã kết thúc ở Deadline 1 (#66), không cần phải làm tiếp các deadline sau nữa.
