### ISSUE TITLE
[L4_TheSun] Nộp deadline #3

### ISSUE THREAD

**Issue by DangNhutYen1212536** [HCMUS-OSSD/HuongdanThuchanh#84]
Chào Thầy, nhóm em xin nộp deadline #3.
 1. Link wiki: https://github.com/HCMUS-OSSD/L4_The-Sun/wiki/%C4%90%E1%BA%B7c-T%E1%BA%A3-Pluggin-FIT-Sale-Manager.
 2. Link Release: https://github.com/HCMUS-OSSD/L4_The-Sun/releases/tag/Deadline3

**Comment by bixycler** [comment]
Duyệt. Nhóm triển khai đi nhé, chỉ còn chưa tới 2 tuần nữa thôi đấy.

**Comment by DangNhutYen1212536** [comment]
Dạ, nhóm em cảm ơn thầy :))
